### ISSUE TITLE
Instructions not complete

### ISSUE THREAD

**Issue by jtsalten** [SergeyMi37/appmsw-telealerts#1]
Trying to install and test the app... following the instructions step by step it doesn't work.
For example, when I load /opt/irisapp this is not asked:
Enter the username of the informer bot  

But this... 
Enter the token to access of the informer bot 

And then, where should we get the token to access?

**Comment by SergeyMi37** [comment]
I will correct the instructions.

**Comment by jtsalten** [comment]
Ok, but in the install process 2 tokens are requested:
![image](https://user-images.githubusercontent.com/6997495/138238234-a830f5a6-1fd3-43db-9e3c-b7b537b9ac35.png)


For the admin bot I’ve used the one that BotFather has given to me… for the informer bot I used the chain you mention in the instructions: sY5NxkS0QXRXdjxmbrIWJWLOA 

Everything seems to go right, but, when I start the production, the service got an error:

![image](https://user-images.githubusercontent.com/6997495/138237376-ccb2e339-68ab-468f-ad94-81d61c994df0.png)

And this is what I got in telestat.bots: 

![image](https://user-images.githubusercontent.com/6997495/138237750-6c30eaab-0d07-4d44-b45f-ee3683bb291d.png)

Sure it's something basic... I'm just blindly following the instructions.

**Comment by jtsalten** [comment]
Ok. I was following instructoins too blindly... I didn't introduce my phone number for the admin... Now that bot works... Not clear but you mean by the bot Informant... you mean a telegram user connected to our bot or actually a different bot? Not clear which is supposed to do that appmsw.telestat.TelegramService ... with by default config gives error because of the token.

**Comment by SergeyMi37** [comment]
You are creating two bots. The first is the admin and the second is the informer. The first one will be used only by you as an administrator, and the name of the second bot can be given to those persons whom you assign the right to use your service.

The token numbers for your bots should only be yours, they did not need to be taken from the instructions. And the mobile number must be yours too.
![image](https://user-images.githubusercontent.com/18187317/139200658-91d924e2-354a-4030-ad11-ad8c6edc9922.png)

Apparently this moment in my instruction was poorly accentuated.

**Comment by SergeyMi37** [comment]
Instruction updated
